---

- name: Install Operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: install
    install_operator_name: "{{ rhsso_operator_name }}"
    install_operator_namespace: "{{ rhsso_operator_namespace }}"
    install_operator_channel: "{{ rhsso_operator_channel }}"
    install_operator_csv_nameprefix: "{{ rhsso_operator_csv_prefix }}"
    install_operator_catalog: "{{ rhsso_operator_catalog }}"
    install_operator_automatic_install_plan_approval: "{{ rhsso_operator_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ rhsso_operator_starting_csv }}"
    install_operator_manage_namespaces:
      - "{{ rhsso_operator_namespace }}"
    install_operator_catalogsource_setup: "{{ rhsso_operator_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name: "{{ rhsso_operator_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace: openshift-operators
    install_operator_catalogsource_image: "{{ rhsso_operator_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag: "{{ rhsso_operator_catalog_snapshot_image_tag | default('') }}"

- name: Wait for rhsso operator to be ready
  when: rhsso_operator_wait_for_deploy | bool
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Deployment
    namespace: "{{ rhsso_operator_namespace }}"
    name: "{{ rhsso_operator_name }}"
  register: r_rhsso_operator_deployment
  retries: 20
  delay: 10
  until:
    - r_rhsso_operator_deployment.resources is defined
    - r_rhsso_operator_deployment.resources | length | int > 0
    - r_rhsso_operator_deployment.resources[0].status.availableReplicas is defined
    - r_rhsso_operator_deployment.resources[0].status.availableReplicas | int == r_rhsso_operator_deployment.resources[0].spec.replicas | int
